'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const app = fs.readFileSync(path.join(__dirname, '..', 'public', 'app.js'), 'utf8');
const html = fs.readFileSync(path.join(__dirname, '..', 'public', 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', 'public', 'style.css'), 'utf8');

test('Edit exposes SAM3, brush, and bounding-box area selection for supported engines', () => {
  assert.match(app, /const EDIT_MASK_ENGINES = new Set\(\['klein4', 'klein9', 'qwen', 'krea2'\]\)/);
  assert.match(html, /id="kreaMaskSmartMode"/);
  assert.match(html, /id="kreaMaskBrushMode"/);
  assert.match(html, /id="kreaMaskBoxMode"/);
  assert.match(html, /id="kreaMaskPrompt"/);
  assert.match(html, /id="kreaMaskPointAdd"/);
  assert.match(html, /id="kreaMaskPointRemove"/);
  assert.match(html, /id="kreaMaskPointDelete"/);
  assert.match(html, /id="kreaMaskBoxControls"/);
  assert.match(html, /id="kreaMaskBoxAdd"/);
  assert.match(html, /id="kreaMaskBoxDelete"/);
  assert.match(html, /id="kreaMaskBoxes"/);
  assert.match(html, /src="\/mask-boxes\.js"[\s\S]*src="\/app\.js"/);
  assert.match(app, /state\.kreaMaskTool === 'box'/);
  assert.match(app, /kreaMaskBoxes: \[\]/);
  assert.match(app, /function beginKreaMaskBoxCreate\(event\)/);
  assert.match(app, /function beginKreaMaskBoxInteraction\(event\)/);
  assert.match(app, /function moveKreaMaskBoxInteraction\(event\)/);
  assert.match(app, /function finishKreaMaskBoxInteraction\(event, cancelled = false\)/);
  assert.match(app, /element\.setAttribute\('role', 'group'\)/);
  assert.match(app, /const grip = document\.createElement\('button'\)/);
  assert.match(app, /maskBoxGeometry\.pixelRects\(boxes, canvas\.width, canvas\.height\)\.forEach/);
  assert.match(app, /context\.fillRect\(rect\.x, rect\.y, rect\.w, rect\.h\)/);
  assert.match(app, /setPointerCapture\?\.\(event\.pointerId\)/);
  assert.match(app, /'pointercancel', \(event\) => finishKreaMaskBoxInteraction\(event, true\)/);
  assert.match(app, /'keydown', keyboardKreaMaskBox/);
  assert.match(app, /function syncKreaMaskCanvasFromState\(\)/);
  assert.match(app, /renderRefs\(\);\s*syncKreaMaskCanvasFromState\(\);/);
  assert.match(app, /function cancelSmartMaskRequest\(\)/);
  assert.match(app, /layer\.hidden = state\.kreaMaskTool !== 'smart'/);
  assert.match(app, /function cancelSmartMaskPointDrag\(\)/);
  assert.match(app, /function cancelKreaMaskBoxInteraction\(\)/);
  assert.match(app, /if \(state\.kreaMaskTool !== 'box' \|\| kreaMaskBoxInteraction/);
  assert.match(app, /requestRevision === smartMaskRequestRevision/);
  assert.match(app, /discardEditableMaskBoxes\(\);[\s\S]*const canvas = \$\('#kreaMaskCanvas'\)/);
  assert.match(app, /if \(state\.kreaMaskTool === 'box'\) \{[\s\S]*beginKreaMaskBoxCreate\(e\)/);
  assert.match(app, /api\('\/api\/edit-mask\/sam3'/);
  assert.match(app, /Array\.isArray\(result\.dataUrls\)/);
  assert.match(app, /globalCompositeOperation = index \? 'lighten' : 'source-over'/);
  assert.match(app, /function beginSmartMaskPointDrag\(event\)/);
  assert.match(app, /function moveSmartMaskPointDrag\(event\)/);
  assert.match(app, /function finishSmartMaskPointDrag\(event\)/);
  assert.match(app, /rerunSmartMaskFromPoints\(\)/);
  assert.match(app, /state\.kreaMaskPointDeleteMode/);
  assert.match(css, /\.edit-area-mode/);
  assert.match(css, /\.smart-mask-point\.dragging/);
  assert.match(css, /\.krea-mask-box-handle \{[\s\S]*?width: 40px;[\s\S]*?height: 40px;/);
  assert.match(css, /\.mask-box-actions button,[\s\S]*?min-height: 44px;/);
  assert.match(css, /\.mask-box-controls\[hidden\]/);
});

test('localized edit requests upload their mask automatically and preserve source-matched output', () => {
  assert.match(app, /supportsCurrentEditMask\(\) && hasEditMask\(\)/);
  assert.match(app, /editAspectOverride: mode === 'edit' && state\.editAspectOverride && !localizedEdit/);
  assert.match(app, /editMaskMode: localizedEdit \|\| preserveMask \? \(state\.kreaMaskKind \|\| state\.kreaMaskTool\)/);
  assert.match(app, /Edit area is active — changes stay inside the mask/);
  assert.match(html, /id="kreaMaskApply">Done/);
});

test('mask refinements visibly apply feathering and invert the current pixels', () => {
  assert.match(html, /id="kreaMaskFeather"/);
  assert.match(html, /id="kreaMaskOffset"[^>]*min="-15"[^>]*max="15"/);
  assert.match(html, /id="kreaMaskInvert"/);
  assert.match(html, /id="kreaMaskViewMode"/);
  assert.match(html, /data-mask-view="dim"/);
  assert.match(html, /data-mask-view="color"/);
  assert.doesNotMatch(html, /id="kreaMaskPreviewToggle"/);
  assert.match(html, /id="kreaMaskCutoutCanvas"/);
  assert.match(html, /id="kreaMaskOverlayCanvas"/);
  assert.match(html, /id="kreaMaskGesture"/);
  assert.match(html, /id="editMaskInfluence"/);
  assert.match(html, /class="edit-mask-adjustments"[\s\S]*id="kreaMaskExpand"[^>]*min="6"[^>]*max="32"[^>]*value="14"/);
  assert.ok(html.indexOf('id="kreaMaskExpand"') > html.indexOf('</main>'), 'Expansion belongs in the mask sheet, not Advanced');
  assert.match(app, /context\.filter = `blur\(\$\{feather\}px\)`/);
  assert.match(app, /function invertKreaMask\(\)/);
  assert.match(app, /const current = \(image\.data\[i\] \* image\.data\[i \+ 3\]\) \/ 255/);
  assert.match(app, /function renderMaskOverlay\(\)/);
  assert.match(app, /function beginMaskGesture\(event\)/);
  assert.match(app, /Brush size \$\{state\.kreaBrush\} px/);
  assert.match(app, /function setSmartMaskLoading\(message\)/);
  assert.match(app, /Still loading SAM3 — first use can take a few minutes/);
  assert.match(app, /d\.kind === 'smartMask' && smartMaskRunning/);
  assert.match(app, /ctx\.globalCompositeOperation = editOutpaintActive\(\) \? 'destination-in' : 'destination-out'/);
  assert.match(app, /ref\.displayUrl = cutout\.toDataURL\('image\/png'\)/);
  assert.match(app, /function scheduleMaskedRefPreview\(\)/);
  assert.match(app, /scheduleMaskedRefPreview\(\);/);
  assert.match(app, /state\.kreaMaskViewMode === 'color'/);
  assert.match(app, /rgba\(0, 0, 0, \.68\)/);
  assert.match(app, /rgba\(255, 102, 93, \.48\)/);
  assert.match(app, /maskInfluence: localizedEdit \? state\.editMaskInfluence/);
  assert.match(app, /maskExpand: localizedEdit \? state\.editMaskExpand/);
  assert.match(app, /function previewMaskCanvas\(\)/);
  assert.match(app, /offsetMaskValues\(values, source\.width, source\.height, expansion, true\)/);
  assert.match(app, /\$\('#kreaMaskExpandField'\)\.hidden = outpaint/);
  assert.match(app, /const out = processedMaskCanvas\(\)/);
  assert.match(app, /function scheduleMaskExpansionPreview\(\)[\s\S]*?renderMaskOverlay\(\);[\s\S]*?refreshMaskCutoutPreview\(\);/);
  assert.match(app, /#kreaMaskExpand'\)\.addEventListener\('input',[\s\S]*?scheduleMaskExpansionPreview\(\);/);
  assert.doesNotMatch(app, /red tint/);
});
